# Settings that differ from Minecraft defaults for this server.
# Minecraft will add other supported properties on first startup.
allow-flight=false
difficulty=easy
enable-rcon=true
enforce-secure-profile=true
gamemode=survival
initial-enabled-packs=vanilla,fabric,fabric-convention-tags-v2,pixelreel
level-name=world
max-players=20
motd=Minecraft Movie Night
online-mode=true
op-permission-level=4
pvp=true
rcon.port=25575
simulation-distance=10
spawn-protection=16
view-distance=10
